# Generated by Django 2.2.6 on 2019-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_profesion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=50)),
                ('description_service', models.CharField(max_length=60)),
                ('rol_profesionals', models.ManyToManyField(blank=True, to='puntos.RolProfesional')),
            ],
        ),
    ]
